# ansible/site.yml
---
- name: Configure Docker-hosted web page
  hosts: all
  become: true
  vars:
    docker_user: ubuntu          # change if you used a different image username
    web_container_name: web
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - docker.io
          - python3-pip          # lets Ansible use docker-py behind the scenes
        state: present
        update_cache: yes
      when: ansible_facts.os_family == "Debian"

    - name: Add {{ docker_user }} to docker group
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes

    - name: Pull nginx image
      community.docker.docker_image:
        name: nginx
        source: pull

    - name: Copy custom index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /opt/index.html
        owner: root
        group: root
        mode: "0644"

    - name: Run nginx container exposing port 80
      community.docker.docker_container:
        name: "{{ web_container_name }}"
        image: nginx
        published_ports:
          - "80:80"
        volumes:
          - /opt/index.html:/usr/share/nginx/html/index.html:ro
        restart_policy: unless-stopped
