# Vagrantfile
Vagrant.configure("2") do |config|
      # Specify the base box image
    config.vm.box = "ubuntu/bionic64"
      # Set the hostname for the VM
    config.vm.hostname = "ansible-vm"
      # Set up a private network with a static IP
    config.vm.network "private_network", ip: "192.168.56.10"
    # Customize VM resources
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
    end
    config.vm.provision "shell", path: "bootstrap.sh"

end

